spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: mirocservicecloud-config-example-dev
---
spring:
  profiles: test
  application:
    name: mirocservicecloud-config-example-test
